

class DataIngestionArtifact:
    pass

class DataValidationArtifact:...
class dataTransformationArtifact:...
class ModelTrainerArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...